---
 # file is parsed by inner-most keys only
 data:
     data_file: "data/intervention_8160.csv"
     debug: True  # Enable debug mode for more info
     batch_size: 1  # 1 for inference, 16 for train
     fci_vars: 3  # Reduced further
     fci_batches: 5  # Reduced further
     fci_batches_inference: 5  # Reduced for small dataset
     fci_batch_size: 20  # Reduced to fit sample data size (100 rows)
     envs_per_batch: 5
     num_workers: 0  # Set to 0 for Windows compatibility
     accumulate_batches: 1
     log_frequency: 10
     results_file: "results_gies.npy"
 model:
     algorithm: "gies"
     model: "aggregator"
     num_vars: 1000
     num_edge_types: 5
     embed_dim: 64
     transformer_num_layers: 4
     n_heads: 8
     ffn_embed_dim: 8
     use_learned_sampler: False
 train:
     run_name: sc-rl
     patience: 50
     epochs: 10000
     min_epochs: 50
     lr: 1.e-4
     weight_decay: 1.e-5
     metric: "Val/auprc"
