---
 # file is parsed by inner-most keys only
 data:
     data_file: "data/intervention_8160.csv"
     debug: False
     batch_size: 1  # 16 for train, 1 for test
     fci_vars: 5
     fci_batches: 10
     fci_batches_inference: 500
     fci_batch_size: 500
     num_workers: 0  # Set to 0 for Windows compatibility
     accumulate_batches: 1
     log_frequency: 10
     results_file: "results_fci.npy"
     use_learned_sampler: False
 model:
     algorithm: "fci"
     model: "aggregator"
     num_vars: 1000
     num_edge_types: 8
     embed_dim: 64
     transformer_num_layers: 4
     n_heads: 8
     ffn_embed_dim: 8
 train:
     run_name: sc-rl
     patience: 50
     epochs: 10000
     min_epochs: 50
     lr: 1.e-4
     weight_decay: 1.e-5
     metric: "Val/auprc"
